version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /mnt/ostrich/BT-Complete:/data/completed
    - /mnt/ostrich/BT-Active:/data/incomplete
    - /mnt/ostrich/kmiyake/Downloads/:/data/watching
    - /home/kmiyake/Developer/docker-transmission-openvpn/openvpn/custom/Trust.Zone-US-CA.ovpn:/etc/openvpn/custom/default.ovpn
  environment:
    - OPENVPN_PROVIDER=CUSTOM
    - OPENVPN_USERNAME=D2iJh
    - OPENVPN_PASSWORD=EfmXpwVS
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.1.0/24
    - TRANSMISSION_WEB_UI=combustion
    - TRANSMISSION_WATCH_DIR_ENABLED=true
    - TRANSMISSION_WATCH_DIR=/data/watching
    - TRANSMISSION_DOWNLOAD_DIR=/data/completed
    - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
    - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
    - TRANSMISSION_PORT_FORWARDING_ENABLED=true
    - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    - TRANSMISSION_RATIO_LIMIT=1.5
    - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true
    - PGID=1000
    - PUID=1000

 proxy:
  image: haugene/transmission-openvpn-proxy
  links:
    - transmission
  ports:
    - 8080:8080
  volumes:
    - /etc/localtime:/etc/localtime:ro

 rss:
  image: haugene/transmission-rss
  links:
    - transmission
  environment:
    - RSS_URL=http://showrss.info/user/20536.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
